// <auto-generated />
namespace BELibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Allow_Null_ReplyFile_StudentTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Allow_Null_ReplyFile_StudentTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202005190200279_Allow_Null_ReplyFile_StudentTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
